site_name: 'Factorio API Documentation'
site_description: 'Unofficial documentation of the Factorio web APIs'
site_url: 'https://artentus.github.io/FactorioApiDoc/'
site_author: 'Mathis Rech'

repo_name: 'Artentus/FactorioApiDoc'
repo_url: 'https://github.com/Artentus/FactorioApiDoc'

theme:
    name: 'material'
    language: 'en'
    favicon: 'assets/images/favicon.ico'
    logo: 'assets/images/logo.svg'

markdown_extensions:
    - toc:
        permalink: "#"

nav:
    - Home: 'index.md'
    - Authentication API:
        - Overview: 'auth-api/index.md'
        - AuthenticationResult Object: 'auth-api/authresult.md'
    - Mod API:
        - Overview: 'mod-api/index.md'
        - ModListPage Object: 'mod-api/modlistpage.md'
        - Pagination Object: 'mod-api/pagination.md'
        - PageLinks Object: 'mod-api/pagelinks.md'
        - ModInfo Object: 'mod-api/modinfo.md'
        - ModRelease Object: 'mod-api/modrelease'
        - License Object: 'mod-api/license'
        - Tag Object: 'mod-api/tag'
    - Matchmaking API:
        - Overview: 'matchmaking-api/index.md'
        - ServerDescription Object: 'matchmaking-api/serverdescription.md'
        - ApplicationVersion Object: 'matchmaking-api/appversion.md'
    - Update API:
        - Overview: 'update-api/index.md'